MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :albums
  resources :bands
  resources :users, :bands, :albums, :tracks
  resource :session

end

MusicApp/app/models/album.rb
class Album < ActiveRecord::Base
  validates :band_id, :album_type, presence: true

  belongs_to :band

  has_many :tracks
end

MusicApp/app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums
end

MusicApp/app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :album_id, :track_type, :lyrics, presence: true

  belongs_to :album
  has_one :band, through: :album, source: :band
end

MusicApp/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.all.find_by(email: email)
    if user
      user = user.is_password?(password) ? user : nil
    end
    user
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end


  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password
    .new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login
    def new
    end

    def create
      @album = Album.new(albums_params)
      if @album.save
        redirect_to album_url(@album.id)
      else
        flash.now[:error] = @album.errors.full_messages
        render :index
      end
    end

    def index
      @albums = Album.all
    end

    def show
      @album = Album.find_by_id(params[:id])
    end

    def edit
      @album = Album.find_by_id(params[:id])
    end

    def update
      @album = Album.find_by_id(params[:id])
      if @album.update(albums_params)
        redirect_to albums_url
      else
        render :edit
      end
    end

    def destroy
      @album = Album.find_by_id(params[:id])
      if @album.destroy
        redirect_to albums_url
      else
        render :index
      end
    end

    private

    def albums_params
      params.require(:album).permit(:band_id, :album_type, :name)
    end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def require_no_user
    @user = current_user
    if @user
      redirect_to user_url(@user.id)
      session[:session_token] = @user.reset_session_token!
    end
  end

  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def require_user
    redirect_to new_session_url
  end

  def require_login
    redirect_to new_session_url unless current_user
  end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login

  def new

  end

  def show
    @band = Band.find_by(id: params[:id])
  end

  def create
    @band = Band.new(bands_params)
    if @band.save
      redirect_to band_url(@band.id)
    else
      flash.now[:error] = @band.errors.full_messages
      render :index
    end
  end

  def index
    @bands = Band.all
  end

  def edit
    @band = Band.find_by(id: params[:id])
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update(bands_params)
      redirect_to bands_url
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    if @band.destroy
      redirect_to bands_url
    else
      render :index
    end
  end

  private

  def bands_params
    params.require(:band).permit(:name)
  end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_user, only: [:new, :create]

  def new
  end

  def create
    email = session_params[:email]
    password = session_params[:password]
    @user = User.find_by_credentials(email, password)
    if @user
      @user.reset_session_token!
      session[:session_token] = @user.session_token
      redirect_to user_url(@user)
    else
      flash.now[:notice] = "Invalid Login or Password"
      render :new
    end
  end

  def destroy
    session[:session_token] = nil
    redirect_to users_url
  end
  private
  def session_params
    params.require(:user).permit(:email, :password)
  end

end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    before_action :require_login
    def new

    end

    def create
      @track = Track.new(tracks_params)
      if @track.save
        redirect_to track_url(@track.id)
      else
        flash.now[:error] = @track.errors.full_messages
        render :index
      end
    end

    def index
      @tracks = Track.all
    end

    def show
      @track = Track.find_by(id: params[:id])
    end

    def edit
      @track = Track.find_by(id: params[:id])
    end

    def update
      @track = Track.find_by(id: params[:id])
      if @track.update(tracks_params)
        redirect_to tracks_url
      else
        render :edit
      end
    end

    def destroy
      @track = Track.find_by(id: params[:id])
      if @track.destroy
        redirect_to tracks_url
      else
        render :index
      end
    end

    private

    def tracks_params
      params.require(:track).permit(:name, :album_id, :track_type, :lyrics)
    end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    set_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        redirect_to users_url
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    set_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password_digest, :session_token, :password)
    end
end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    text = "<input type=\"hidden\" name=\"authenticity_token\" value= \"<%=form_authenticity_token=>\" >"
    text.html_safe
  end
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MusicApp/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<form action= <%= album_url(@album) %> method="post">
  <input type="hidden" name="_method" value="put">
  <%= auth_token %>
  <label for="album_band_id">Select Band</label>
  <select  name="album[band_id]", id="album_band_id">
    <% Band.all.each do |band| %>
    <option value="<%= band.id %>" <%= @album.band.name == band.name ? "selected" : "" %>> <%= band.name %></option>
    <% end %>
  </select><br>
  <label for="album_name">Album Name</label>
  <input type="text" name="album[name]" id="album_name", value = <%= @album.name %>><br>
  <input type="radio" name="album[album_type]", value="Live" <%= @album.album_type == "Live" ? "checked" : "" %>>Live<br>
  <input type="radio" name="album[album_type]", value="Studio" <%= @album.album_type == "Studio" ? "checked" : "" %>>Studio<br>
  <input type="submit" value="Edit Album">
</form>

<%= link_to 'Back', albums_path %>

MusicApp/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Albums</h1>
<%= auth_token %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <%= link_to "#{album.name}", album_url(album) %><br>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>
<%= link_to 'Bands', bands_url %>
<%= link_to 'Tracks', tracks_url %>
<%= link_to "User", user_url(current_user) %>

MusicApp/app/views/albums/new.html.erb
<h1>New Album</h1>

<form action= <%= albums_url %> method="post">
  <%= auth_token %>
  <label for="album_band_id">Select Band</label>
  <select  name="album[band_id]", id="album_band_id">
    <% Band.all.each do |band| %>
    <option value="<%= band.id %>"> <%= band.name %></option>
    <% end %>
  </select><br>
  <label for="album_name">Album Name</label>
  <input type="text" name="album[name]" id="album_name"><br>
  <input type="radio" name="album[album_type]", value="Live">Live<br>
  <input type="radio" name="album[album_type]", value="Studio">Studio<br>
  <input type="submit" value="Create Album">
</form>

<%= link_to 'Back', albums_path %>

MusicApp/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @album.name %></h1>

<% @album.tracks.each do |track| %>
  <%= link_to "#{track.name}", track_url(track) %><br>
<% end %>

<%= link_to 'Back', albums_path %>
<%= link_to 'Edit', edit_album_path(@album) %>

MusicApp/app/views/bands/Albums.html.erb
<h1>Bands#Albums</h1>
<p>Find me in app/views/bands/Albums.html.erb</p>

MusicApp/app/views/bands/Tracks.html.erb
<h1>Bands#Tracks</h1>
<p>Find me in app/views/bands/Tracks.html.erb</p>

MusicApp/app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MusicApp/app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<form action= <%= band_url(@band) %> method = 'post'>
  <input type="hidden" name="_method" value="put">
  <%= auth_token %>
  <label for="name">Band Name</label>

  <input type="text" name ="band[name]" id="name", value= <%= @band.name %>>

  <input type="submit" value="Edit band">
</form>
<%= link_to 'Back', bands_path %>

MusicApp/app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bands</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
       <%= link_to "#{band.name}", band_url(band) %><br>
        <!--
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>
<%= link_to 'Albums', albums_url %>
<%= link_to 'Tracks', tracks_url %>
<%= link_to "User", user_url(current_user) %>

MusicApp/app/views/bands/new.html.erb
<h1>New Band</h1>

<form action= <%= bands_url %> method = 'post'>
  <%= auth_token %>
  <label for="name">Band Name</label>

  <input type="text" name ="band[name]" id="name">

  <input type="submit" value="Create band">
</form>
<%= link_to 'Back', bands_path %>

MusicApp/app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @band.name %></h1>
<p>
  <% @band.albums.each do |album| %>
    <%= link_to "#{album.name}", album_url(album)%>
  <% end %>
</p>
<%= link_to 'Delete', band_url(@band), method: "delete" %>
<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MusicApp/app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MusicApp/app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<form action= <%= track_url(@track) %> method="post">
  <input type="hidden" name="_method" value="put">
  <%= auth_token %>

  <label for="track_album_id">Select Album</label>
  <select  name="track[album_id]", id="track_album_id">
    <% Album.all.each do |album| %>
    <option value="<%= album.id %>" <%= @track.album.name == album.name ? "selected" : "" %>> <%= album.name %></option>
    <% end %>
  </select><br>

  <label for="track_name">Track Name</label>

  <input type="text" name="track[name]" id="track_name" value = <%= @track.name %>><br>

  <input type="radio" name="track[track_type]", value="Bonus" <%= @track.track_type == "Bonus" ? "checked" : "" %> >Bonus<br>

  <input type="radio" name="track[track_type]", value="Regular" <%= @track.track_type == "Regular" ? "checked" : "" %>>Regular<br>

  <textarea name="track[lyrics]" rows="8" cols="80" id="lyrics"><%=@track.lyrics%></textarea><br>
  
  <input type="submit" value="Edit track">
</form>

<%= link_to 'Back', tracks_path %>

MusicApp/app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tracks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <%= link_to "#{track.name}", track_url(track) %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>
<%= link_to 'Albums', albums_url %>
<%= link_to 'Bands', bands_url %>
<%= link_to "User", user_url(current_user) %>

MusicApp/app/views/tracks/new.html.erb
<h1>New Track</h1>

<form action= <%= tracks_url %> method="post">
  <%= auth_token %>
  <label for="track_album_id">Select Album</label>
  <select  name="track[album_id]", id="track_album_id">
    <% Album.all.each do |album| %>
    <option value="<%= album.id %>"> <%= album.name %></option>
    <% end %>
  </select><br>
  <label for="track_name">Track Name</label>
  <input type="text" name="track[name]" id="track_name"><br>
  <input type="radio" name="track[track_type]", value="Bonus">Bonus<br>
  <input type="radio" name="track[track_type]", value="Regular">Regular<br>
  <textarea name="track[lyrics]" rows="8" cols="80" id="lyrics">Lyrics</textarea><br>
  <input type="submit" value="Create track">
</form>

<%= link_to 'Back', tracks_path %>

MusicApp/app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<td>Track Name: </td> <%= @track.name %><br>
<td>  Album: </td> <%= link_to "#{@track.album.name}", album_url(@track.album) %><br>
<td>Type: </td> <%= @track.track_type %><br>
<td>Band: </td> <%= link_to "#{@track.band.name}", band_url(@track.band) %><br>
<td>Lyrics: </td> <%= @track.lyrics %><br>
<br>
<%= link_to 'Delete', track_url(@track), method: 'delete' %>
<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>

MusicApp/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

MusicApp/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user, index| %>
      <tr>
        <td><%= index %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Login', new_session_url %>

MusicApp/app/views/users/new.html.erb
<h1>New User</h1>

<form action= <%= users_url %> method="post" >
   <%= auth_token %>
    <label for="email">Email</label>
    <input type="text" name="user[email]" id="email">

    <label for="Password">Password</label>
    <input type="pasword" name="user[password]">

    <input type="submit" value="Create User">
</form>

<%= link_to 'Back', users_path %>

MusicApp/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Session token:</strong>
  <%= @user.session_token %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Delete', user_url(@user.id) ,confirm: 'Are you sure?', method: 'DELETE' %>
<%= link_to 'LogOut', session_url, method: 'delete'  %>
<br>
<%= link_to 'Albums', albums_url %>
<%= link_to 'Tracks', tracks_url %>
<%= link_to 'Bands', bands_url %>